clinica/urls.py
from django.conf.urls import url
from . import views

# /clinica/

app_name='clinica'

urlpatterns =[

	url(r'^$', views.cajero, name='cajero'),
	url(r'^admin/$', views.admin, name='admin'),
	url(r'^medic/$', views.medi, name='medi'),
	url(r'^farmaceutico/$', views.farma, name='farma'),
	
	url(r'^configuracion/$', views.configuracion, name='configuracion'),

	url(r'^paciente/$', views.paciente, name='paciente'),
	url(r'^paciente/(?P<id>\d+)/$', views.editarpaciente, name='editarpaciente'),
	url(r'^paciente/nuevo/$', views.nuevopaciente, name='nuevopaciente'),
	url(r'^paciente/buscar/$', views.buscarpaciente, name='buscarpaciente'),

	url(r'^medico/$', views.medico, name='medico'),
	url(r'^medico/(?P<id>\d+)/$', views.editarmedico, name='editarmedico'),
	url(r'^medico/nuevo/$', views.nuevomedico, name='nuevomedico'),
	# url(r'^medico/buscar/$', views.buscarmedico, name='buscarmedico'),

	url(r'^empleado/$', views.empleado, name='empleado'),
	url(r'^empleado/(?P<id>\d+)/$', views.editarempleado, name='editarempleado'),
	url(r'^empleado/nuevo/$', views.nuevoempleado, name='nuevoempleado'),
	url(r'^empleado/buscar/$', views.buscarempleado, name='buscarempleado'),

	url(r'^cargo/$', views.cargo, name='cargo'),
	url(r'^cargo/(?P<id>\d+)/$', views.editarcargo, name='editarcargo'),
	url(r'^cargo/nuevo/$', views.nuevocargo, name='nuevocargo'),

	url(r'^especialidad/$', views.especialidad, name='especialidad'),
	url(r'^especialidad/(?P<id>\d+)/$', views.editarespecialidad, name='editarespecialidad'),
	url(r'^especialidad/nuevo/$', views.nuevoespecialidad, name='nuevoespecialidad'),

	url(r'^usuario/$', views.usuario, name='usuario'),
	url(r'^usuario/nuevo/$', views.nuevousuario, name='nuevousuario'),

	url(r'^local/$', views.local, name='local'),
	url(r'^local/(?P<id>\d+)/$', views.editarlocal, name='editarlocal'),
	url(r'^local/nuevo/$', views.nuevolocal, name='nuevolocal'),

	url(r'^proveedor/$', views.proveedor, name='proveedor'),
	url(r'^proveedor/(?P<id>\d+)/$', views.editarproveedor, name='editarproveedor'),
	url(r'^proveedor/nuevo/$', views.nuevoproveedor, name='nuevoproveedor'),

	url(r'^profesion/$', views.profesion, name='profesion'),
	url(r'^profesion/(?P<id>\d+)/$', views.editarprofesion, name='editarprofesion'),
	url(r'^profesion/nuevo/$', views.nuevoprofesion, name='nuevoprofesion'),

	url(r'^medicamento/$', views.medicamento, name='medicamento'),
	url(r'^medicamento/(?P<id>\d+)/$', views.editarmedicamento, name='editarmedicamento'),
	url(r'^medicamento/nuevo/$', views.nuevomedicamento, name='nuevomedicamento'),

	url(r'^diagnostico/$', views.diagnostico, name='diagnostico'),
	url(r'^diagnostico/(?P<id>\d+)/$', views.editardiagnostico, name='editardiagnostico'),
	url(r'^diagnostico/nuevo/$', views.nuevodiagnostico, name='nuevodiagnostico'),

	url(r'^prescripcion/(?P<id>\d+)/$', views.prescripcion, name='prescripcion'),
	url(r'^prescripcion/add/$', views.addprescripcion, name='addprescripcion'),

	url(r'^historial/(?P<id>\d+)/$', views.historial, name='historial'),
	
	url(r'^pago/$', views.listacobro, name='listacobro'),
	url(r'^pago/(?P<id>\d+)/$', views.pago, name='pago'),
	url(r'^pago/recibo/(?P<id>\d+)/$', views.recibo, name='recibo'),

	url(r'^venta/$', views.venta, name='venta'),
	url(r'^venta/nuevo/$', views.nuevoventa, name='nuevoventa'),

	url(r'^venta/(?P<id>\d+)/detalle/$', views.detalle, name='detalle'),
	url(r'^detalle/nuevo/(?P<id>\d+)/$', views.nuevodetalle, name='nuevodetalle'),



	

]

clinicaChevez/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from security.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^security/', include('security.urls')),
    url(r'^clinica/', include('clinica.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

security/urls.py
from django.conf.urls import url
from . import views

# /security/ 

app_name='security'

urlpatterns =[
	url(r'^loginform/', views.login_form, name='login_form'),
	url(r'^login/$', views.log_in, name='log_in'),
	url(r'^logout/$', views.log_out, name='log_out'),
]

clinica/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.


# CATALOGOS
@python_2_unicode_compatible
class Cargo(models.Model):
	cargo=models.CharField(max_length=25)

	def __str__(self):
		return self.cargo

@python_2_unicode_compatible
class Sexo(models.Model):
	sexo=models.CharField(max_length=25)

	def __str__(self):
		return self.sexo		

@python_2_unicode_compatible
class EstadoCivil(models.Model):
	estadocivil=models.CharField(max_length=25)

	def __str__(self):
		return self.estadocivil

@python_2_unicode_compatible
class Profesion(models.Model):
	profesion=models.CharField(max_length=25)

	def __str__(self):
		return self.profesion
# Transaccionales

@python_2_unicode_compatible
class Local(models.Model):
	nombre=models.CharField(max_length=5)
	ancho=models.FloatField()
	largo=models.FloatField()
	precio=models.DecimalField(max_digits=7, decimal_places=2)
	estado=models.BooleanField(default=True)
	
	def __str__(self):
		return self.nombre

@python_2_unicode_compatible
class Empleado(models.Model):
	nombre=models.CharField(max_length=50)
	apellido=models.CharField(max_length=50)
	direccion=models.TextField()
	celular=models.CharField(max_length=9)
	telcasa=models.CharField(max_length=9)
	correo=models.EmailField()
	fechanacimiento=models.DateField()
	fechacontratacion=models.DateTimeField()
	titulo=models.CharField(max_length=75)
	sexo=models.ForeignKey(Sexo)
	estadocivil=models.ForeignKey(EstadoCivil)
	cargo=models.ForeignKey(Cargo)
	local=models.ForeignKey(Local)
	user= models.OneToOneField(User, null=True)
	estado=models.BooleanField()

	def __str__(self):
		return self.nombre +' '+ self.apellido

@python_2_unicode_compatible
class Paciente(models.Model):
	identidad= models.CharField(max_length=15)
	nombre=models.CharField(max_length=50)
	apellido=models.CharField(max_length=50)
	direccion=models.TextField()
	celular=models.CharField(max_length=9, null=True)
	telcasa=models.CharField(max_length=9, null=True)
	correo=models.EmailField(null=True)
	fechanacimiento=models.DateTimeField()
	sexo=models.ForeignKey(Sexo)
	profesion=models.ForeignKey(Profesion)
	estadocivil=models.ForeignKey(EstadoCivil)


	def __str__(self):
		return self.nombre +' '+ self.apellido

@python_2_unicode_compatible
class Proveedor(models.Model):
	nombre=models.CharField(max_length=50)
	apellido=models.CharField(max_length=50)
	direccion=models.TextField()
	celular=models.CharField(max_length=9, null=True)
	correo=models.EmailField(null=True)
	sexo=models.ForeignKey(Sexo)
	empresa=models.CharField(max_length=50)
	

	def __str__(self):
		return self.nombre +' '+ self.apellido+': '+self.empresa

@python_2_unicode_compatible
class Medicamento(models.Model):
	nombre=models.CharField(max_length=50)
	descripcion=models.CharField(max_length=100)
	existencia=models.IntegerField()
	precio=models.DecimalField(max_digits=5, decimal_places=2)
	fechaelaboracion=models.DateField()
	fechaVencimiento=models.DateField()
	proveedor=models.ForeignKey(Proveedor)
	
	def __str__(self):
		return self.nombre

@python_2_unicode_compatible
class Configuracion(models.Model):
	nombre_empresa=models.CharField(max_length=70)
	logo=models.ImageField(upload_to='Logo')
	ubicacion=models.TextField()
	RTN=models.CharField(max_length=20)
	correo=models.EmailField()
	celular=models.CharField(max_length=9)

	def __str__(self):
		return self.nombre_empresa

@python_2_unicode_compatible
class Diagnostico(models.Model):
	paciente=models.ForeignKey(Paciente)
	empleado=models.ForeignKey(Empleado)
	fecha=models.DateField(auto_now_add=True)
	descripcion=models.TextField()

	def __str__(self):
		return self.descripcion		

@python_2_unicode_compatible
class Prescripcion(models.Model):
	diagnostico=models.ForeignKey(Diagnostico)
	medicamento=models.ForeignKey(Medicamento)
	dosis=models.CharField(max_length=50)
	tiempo=models.CharField(max_length=50)

	def __str__(self):
		return '{}: {}'.format(self.diagnostico, self.medicamento)

@python_2_unicode_compatible
class PagoConsulta(models.Model):
	fecha=models.DateField(auto_now_add=True)
	paciente=models.ForeignKey(Paciente)
	empleado=models.ForeignKey(Empleado)
	precio=models.DecimalField(max_digits=5, decimal_places=2)
	estado=models.BooleanField(default=False)

	def __str__(self):
		return'{}:{}'.format( str(self.fecha.strftime("%d/%m/%y")),self.paciente)

@python_2_unicode_compatible
class VentaMedicamento(models.Model):
	fecha=models.DateField(auto_now_add=True)
	empleado=models.ForeignKey(Empleado)
	paciente=models.ForeignKey(Paciente)
	
	def __str__(self):
		return '{}:{}'.format(str(self.fecha.strftime("%d/%m/%y")),self.paciente)

@python_2_unicode_compatible
class DetalleVenta(models.Model):
	ventamedicamento=models.ForeignKey(VentaMedicamento)
	medicamento=models.ForeignKey(Medicamento)
	cantidad=models.IntegerField()
	subtotal=models.FloatField(default=0,editable=False)
	
	def __str__(self):
		return '{}:{}'.format(self.ventamedicamento.paciente,self.medicamento)

	def save(self,*args,**kwargs):
		self.subtotal=(float(self.medicamento.precio)*float(self.cantidad))
		super(DetalleVenta,self).save(*args,**kwargs)

@python_2_unicode_compatible
class Especialidad(models.Model):
	empleado=models.ForeignKey(Empleado)
	especialidad=models.CharField(max_length=50)

	def __str__(self):
		return '{}: {}'.format(self.empleado,self.especialidad)

clinica/forms.py
from django.forms import ModelForm 
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm

class PacienteForm(ModelForm):
	class Meta:
		model = Paciente
		fields= '__all__'
		widgets={
				'direccion': forms.Textarea(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),
				'correo': forms.EmailInput(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),
				'fechanacimiento': forms.DateInput(format=('%d-%m-%Y'),attrs={
					'class': 'form-control',
					'autofocus':'autofocus',
					'type':'date'
					}),

		}

class EmpleadoForm(ModelForm):
	class Meta:
		model = Empleado
		fields= '__all__'
		widgets={
				'direccion': forms.Textarea(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),
				'correo': forms.EmailInput(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),
				'fechanacimiento': forms.DateInput(format=('%d-%m-%Y'),attrs={
					'class': 'form-control',
					'autofocus':'autofocus',
					'type':'date'
					}),
				'fechacontratacion': forms.DateInput(format=('%d-%m-%Y'),attrs={
					'class': 'form-control',
					'autofocus':'autofocus',
					'type':'date'
					}),
				'estado': forms.CheckboxInput(attrs={
					'class': 'form-control',
					'autofocus':'autofocus',
					'type':'date'
					}),

		}

class CargoForm(ModelForm):
	class Meta:
		model = Cargo
		fields= '__all__'
		widgets={
				'cargo': forms.TextInput(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),

		}

class ProveedorForm(ModelForm):
	class Meta:
		model = Proveedor
		fields= '__all__'
		widgets={
				'direccion': forms.Textarea(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),
				'correo': forms.EmailInput(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),
			}

class ProfesionForm(ModelForm):
	class Meta:
		model = Profesion
		fields= '__all__'
		widgets={
			}

class MedicamentoForm(ModelForm):
	class Meta:
		model = Medicamento
		fields= '__all__'
		widgets={
			'fechaelaboracion': forms.DateInput(format=('%d-%m-%Y'),attrs={
					'class': 'form-control',
					'autofocus':'autofocus',
					'type':'date'
					}),
			'fechaVencimiento': forms.DateInput(format=('%d-%m-%Y'),attrs={
					'class': 'form-control',
					'autofocus':'autofocus',
					'type':'date'
					}),
			}

class EspecialidadForm(ModelForm):
	class Meta:
		model = Especialidad
		fields= '__all__'
		widgets={

		}

class DiagnosticoForm(ModelForm):
	class Meta:
		model = Diagnostico
		fields= '__all__'
		widgets={

		}

class ConfiguracionForm(ModelForm):
	class Meta:
		model= Configuracion
		fields= '__all__'
		widgets={
			'logo': forms.FileInput(attrs={
				'class':'form-control',
				'autofocus':'autofocus'
				}),
			'ubicacion': forms.Textarea(attrs={
				'class':'form-control',
				'autofocus':'autofocus'
				}),
			'correo': forms.EmailInput(attrs={
					'class': 'form-control',
					'autofocus':'autofocus'
					}),

		}

class LocalForm(ModelForm):
	class Meta:
		model = Local
		fields= '__all__'
		widgets={
		
		}

class PrescripcionForm(ModelForm):
	class Meta:
		model = Prescripcion
		fields= '__all__'
		widgets={
			'diagnostico':forms.HiddenInput(attrs={}),
		}

class UsuarioForm(UserCreationForm):
	class Meta:
		model =User
		fields= ['username','first_name', 'last_name', 'password1', 'password2']


class VentaMedicamentoForm(ModelForm):
	empleado=forms.ModelChoiceField(queryset=Empleado.objects.filter(cargo=Cargo.objects.get(pk=4)))
	class Meta:
		model = VentaMedicamento
		fields= '__all__'
		widgets={
		
		}

class DetalleVentaForm(ModelForm):
	class Meta:
		model = DetalleVenta
		fields= '__all__'
		widgets={
		
		}
		

clinica/templates/admin.html
{% extends "base_in.html" %}

{% block title %}
	Bienvenido Administrador
{% endblock %}

{% load static %}

{% block fondo %}
	{% static 'media/imagen3.jpg' %}
{% endblock fondo %}

{% block body %}
	
	<div class="row">
		<div class="col-md-12" style="margin: auto; display:block; ">
			<img src="{% static '/media/logo.png' %}" alt="img" style="margin: auto; display:block; ">
			<hr>
		</div>


		<div class="btn-group">

			<button type="button" class="btn btn-secondary">
				<a href="{% url 'clinica:admin' %}">
					<img src="{% static '/media/home.png' %}" alt="img" style="margin: auto;width:45px" >
				</a>
			</button>
			<button type="button" class="btn btn-secondary" >
				<a href="{% url 'clinica:paciente' %}">
					<img src="{% static '/media/paciente.png' %}" alt="img" style="margin: auto;width:45px" >
				</a><a href="{% url 'clinica:paciente' %}" style="color:white"><strong>  PACIENTE</strong></a>
			</button>
			<button type="button" class="btn btn-secondary" >
				<a href="{% url 'clinica:medico' %}">
					<img src="{% static '/media/medico.png' %}" alt="img" style="margin: auto;width:45px" >
				</a><a href="{% url 'clinica:medico' %}" style="color:white"><strong>  MEDICO</strong></a>
			</button>
			<button type="button" class="btn btn-secondary">
				<a href="{% url 'clinica:empleado' %}">
					<img src="{% static '/media/empleado.png' %}" alt="img" style="margin: auto;width:45px" >
				</a><a href="{% url 'clinica:empleado' %}" style="color:white"><strong>  EMPLEADO</strong></a>
			</button>

			<button type="button" class="btn btn-secondary">
				<a href="{% url 'clinica:diagnostico' %}">
					<img src="{% static '/media/consultamedica.png' %}" alt="img" style="margin: auto;width:40px" >
				</a><a href="{% url 'clinica:diagnostico' %}" style="color:white"><strong>  CONSULTAS MEDICAS</strong></a>
			</button>

		  	<div class="btn-group" role="group">
		    	<button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		      	<img src="{% static '/media/registro.png' %}" alt="img" style="margin: auto;width:50px" ><strong>  REGISTROS</strong>
		    	</button>
		    	<div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
		      		<a class="dropdown-item" href="{% url 'clinica:cargo' %}">Cargo</a>
		        	<a class="dropdown-item" href="{% url 'clinica:especialidad' %}">Especialidad</a>
		        	<a class="dropdown-item" href="{% url 'clinica:usuario' %}">Usuario</a>
		        	<a class="dropdown-item" href="{% url 'clinica:local' %}">Local</a>
		        	<a class="dropdown-item" href="{% url 'clinica:medicamento' %}">Medicamento</a>
		        	<a class="dropdown-item" href="{% url 'clinica:profesion' %}">Profesión</a>
		        	<a class="dropdown-item" href="{% url 'clinica:proveedor' %}">Proveedor</a>
		   		</div>
		  	</div>


		  	<div class="btn-group" role="group">
		    	<button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		      	<img src="{% static '/media/pagos.png' %}" alt="img" style="margin: auto;width:50px" ><strong>  PAGOS</strong>
		    	</button>
		    	<div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
		      		<a class="dropdown-item" href="{% url 'clinica:listacobro' %}">Consulta</a>
		        	<a class="dropdown-item" href="{% url 'clinica:venta' %}">Medicamento</a>
		   		</div>
		  	</div>

		  	<div class="btn-group" role="group">
		    	<button id="btnGroupDrop3" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		      	<img src="{% static '/media/configuracion.png' %}" alt="img" style="margin: auto;width:50px" ><strong>  </strong>
		    	</button>
		    	<div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
		      		<a class="dropdown-item" href="{% url 'security:log_out' %}"><img src="{% static '/media/cerrarsesion.png' %}" alt="img" style="margin: auto;width:30px" >  Cerrar Sesión</a>
		   		</div>
		  	</div>
		</div>

		<div class="col-md-12" style="text-align:center">
			<br>
			<br>
			<center>
				<form class="form-inline col-md-12">
					<div style="width:50px;" class="col-md-3">
						<img class="card-img-top" src="{% static '/media/pacienteprin.png' %}" alt="Card image cap">
						<div>
							<p class="card-text" style="text-align:center"><strong>Pacientes:  {{paciente}}</strong></p>
						</div>
					</div>
					<div class="col-md-1"></div>
					<div style="width:50px;" class="col-md-3">
						<img class="card-img-top" src="{% static '/media/medicoprin.png' %}" alt="Card image cap">
						<div>
							<p class="card-text" style="text-align:center"><strong>Empleados:  {{empleado}}</strong></p>
						</div>
					</div>
					<div class="col-md-1"></div>
					<div style="width:50px;" class="col-md-3">
						<img class="card-img-top" src="{% static '/media/consultasprin.png' %}" alt="Card image cap">
						<div>
							<p class="card-text" style="text-align:center"><strong>Diagnosticos:  {{diagnostico}}</strong></p>
						</div>
					</div>
					<div class="col-md-1"></div>
				</form>
			</center>
			<br>
			<p style="color:blue"><strong>Somos una red de Clínica y Centros médicos a nivel nacional, con la tecnología más moderna y el Staff médico más comprometido con la salud de nuestros pacientes y la de su familia.</strong></p>
		</div>
	</div>
	
	
	

	
	
{% endblock  %}

clinica/templates/configuracion.html
{% extends "base_in.html" %}

{% block title %}
	Edición de Paciente
{% endblock %}


{% block body %}
		
		<div class="col-md-5" style="margin:0 auto" id="form">
			<form method="post" >
					{% csrf_token %}
					{{ form.as_p}}
					<input type="submit" value="Save" class="btn btn-success">
			</form>			
		</div>
	
{% endblock  %}

clinica/templates/consultamedica.html
{% extends "base_in.html" %}

{% block title %}
	Consulta Medica
{% endblock %}

{% load static %}

{% block fondo %}
	{% static 'media/fconsultamedica.jpg' %}
{% endblock %}

{% block body %}

	<div class="row ">
		
		<div class="col-md-12" style="width:1130px;height:150px; margin:0 auto;border-radius:3px;position:static">
			<img src="{% static '/media/logo.png' %}" alt="img" style="margin: auto;psoition:absolute ">
			<br>
		</div>
		
		<nav class="navbar navbar-dark bg-dark col-md-12">
			<nav class="col-md-12" >
  				<form class="form-inline">
  					<div class="col-md-2">	
  						<a href="{% url 'clinica:admin' %}" type="buttonCerrarSesion"style="position:static; display:inline-block; "><img src="{% static '/media/regresar.png' %}" alt="img" style="margin: auto;width:100%; align:right" ></a> 
  					</div>

  					<div class="col-md-8" >
	    				<label style="color:white; font-size:20px">CONSULTAS MEDICAS </label>
  					</div>
  					<div class="col-md-2" >
	    				<button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal" >
	    					<img src="{% static '/media/nuevo.png' %}" alt="img" style="margin: auto;width:25px; align:right" ><strong>  NUEVO</strong>
	    				</button>
	   					<a href="{% url 'security:log_out' %}" type="buttonCerrarSesion"style="position:absolute; float:right; display:inline-block"><img src="{% static '/media/cerrarsesion.png' %}" alt="img" style="margin: auto;width:40px; align:right" ></a>    					
	    				
  					</div>

  				</form>
			</nav>
		</nav>

		<table class="table table-striped " >
			<thead class="table-dark">	
				<tr style="text-align:center">
					<th>#</th>
					<th>Paciente</th>
					<th>Descripcion</th>
					<th>Medico</th>
					<th>Fecha</th>
					<th>Asignación</th>
					<th>Acciones</th>
				</tr>
			</thead>

			<tbody style="background:#F2F3F5;text-align:center">
				{% for p in consulta %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td><strong>{{p.paciente.nombre}} {{p.paciente.apellido}}</strong></td>
						<td>{{p.descripcion}}</td>
						<td>{{p.empleado.nombre}} {{p.empleado.apellido}}</td>
						<td>{{p.fecha}}</td>
						<td>
							<div class="btn">
								<a class="dropdown-item" href="{% url 'clinica:prescripcion' p.id %}">
					    			<img src="{% static '/media/medicamento.png' %}" alt="img" style="margin: auto;width:30px; align:right" ><strong>  Medicamento</strong>
					    		</a>
							</div>
						</td>
						<td>
							<div class="btn-group" role="group" style="color:orange">
			    				<button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
									<img src="{% static '/media/accion.png' %}" alt="img" style="margin: auto;width:20px; align:right" >
			    				</button>

						    	<div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
						    		<a class="dropdown-item" href="{% url 'clinica:editardiagnostico' p.id %}">
						    			<img src="{% static '/media/editar.png' %}" alt="img" style="margin: auto;width:20px; align:right" ><strong>  Editar</strong>
						    		</a>
						      		<a class="dropdown-item" href="{% url 'clinica:historial' p.paciente.id %}">
						      			<img src="{% static '/media/historial.png' %}" alt="img" style="margin: auto;width:20px; align:right" ><strong>  Historial</strong>
						      		</a>
						    	</div>
					  		</div>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>


	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel"><img src="{% static '/media/nuevo.png' %}" alt="img" style="margin: auto;width:30px" > Nueva Consulta</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	<form  action="{%  url 'clinica:nuevodiagnostico' %}" method="post">
					{% csrf_token %}
					{{ form.as_p}}
					<input type="submit" value="Guardar" class="btn btn-success">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</form>
	      </div>
	    </div>
	  </div>
	</div>
	
	<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel"><img src="{% static '/media/nuevo.png' %}" alt="img" style="margin: auto;width:30px" > Nuevo Paciente</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        <form  action="{%  url 'clinica:nuevopaciente' %}" method="post">
	        	<div class="col-md-12">
	        		
					{% csrf_token %}
					{{ form.as_p}}
					<input type="submit" value="Guardar" class="btn btn-success">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
	        	</div>
			</form>
	      </div>
	    </div>
	  </div>
	</div>
	
{% endblock %}